use_frameworks!

target 'WRCalendarView_Example' do
  pod 'WRCalendarView', :path => '../'
  pod 'DropDownMenuKit'
  
  target 'WRCalendarView_Tests' do
    inherit! :search_paths

    pod 'Quick', '1.2.0'
    pod 'Nimble', '7.0.2'
  end
end
